### ISSUE TITLE
failed to connect to 'ipv4:10.160.113.47:2222': socket error: connection refused

### ISSUE THREAD

**Issue by echoyes** [caicloud/tensorflow-demo#13]
when I run the distributed mnist_cnn.py and I just followed the comand like this "./start_tf.sh 8 3 mnist_cnn.py", I encountered some errors such as "failed to connect to 'ipv4:10.160.113.47:2222': socket error: connection refused" .  
Besides, I am  also wondering by using the command  "./start_tf.sh 8 3 mnist_cnn.py"  how to start remote server process without using ssh or some other protocols.  
thanks.

**Comment by perhapszzy** [comment]
You should run the start_tf.sh inside the k8s cluster. That means you need to use 
`kubectl exec -it some-pod bash`
to go into the cluster and start the training process. `some-pod` could be any pod that runs inside the cluster. For example you use the ps-worker pod.

If you want to train models using remote server, TensorFlow uses gRPC by default (and I don't think you can change that without significant code change).

**Comment by guiyang882** [comment]
您好！
您已经开源了自己的v1.0版本的代码，我想问下，如果自己搭建起来了kubernetes集群后，将您的v1.0版本的代码整合到想有集群中，可行么？

谢谢🙏
