### ISSUE TITLE
如何申请账号，下载docker image ？

### ISSUE THREAD

**Issue by guiyang882** [caicloud/tensorflow-demo#14]

**Comment by perhapszzy** [comment]
cargo.caicloud.io/tensorflow/tensorflow:1.0.0 等镜像是不需要账号的

**Comment by guiyang882** [comment]
您好！这个账号确实时可以运行，但是仅仅能运行tensorfflow，我其实想运行分布式版本的tensorflow，因此想申请您的账号，能不能运行分布式版本的tensorflow！像您给到的这样！
[图片如下](https://github.com/caicloud/tensorflow-demo/raw/master/picture/dist_creation.png)

**Comment by perhapszzy** [comment]
我们平台目前处在内测状态，是邀请注册的。之后公测开始之后就可以使用分布式了，具体情况请关注我们caicloud公众号
![image](https://cloud.githubusercontent.com/assets/7953637/25264345/e15a0f62-2698-11e7-9046-e7b903157d80.png)

**Comment by guiyang882** [comment]
你好！能给我分享一个测试账号么？

**Comment by perhapszzy** [comment]
请在http://caicloud.mikecrm.com/9nLwGPi申请，谢谢

**Comment by guiyang882** [comment]
好的，谢谢您了！我对您公司内部的分布式tensorflow集群的设计很感兴趣，希望多多与您交流！
